#!/bin/sh

mkdir -p doc
cd doc
git clone git@github.com:nanofi/nanofi-lib.git .
git checkout gh-pages
cd ..
ant -f javadoc.xml
cd doc
git add .
git commit -a -m "Update javadoc from master"
git push origin gh-pages
cd ..
rm -rf doc
